apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volume:
      - name: dir
        hostpath:
          path: /src
      - name: config
        configMap:
          name: nginx-config
          key: config
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: dir
            mountPath: /src
          - name: config
            mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
